// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT1rQR4mbyVFfl4jEN1avYL83oVEt5kRo',
    appId: '1:162614977353:android:281b01f4e780855f4e3098',
    messagingSenderId: '162614977353',
    projectId: 'basket-3ab3a',
    storageBucket: 'basket-3ab3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw5rjOzcZjq1V0AUQwTO2RPrSa1cLZURQ',
    appId: '1:162614977353:ios:15448ba82e4a93b94e3098',
    messagingSenderId: '162614977353',
    projectId: 'basket-3ab3a',
    storageBucket: 'basket-3ab3a.firebasestorage.app',
    iosBundleId: 'com.arjunyuvaraj.basket',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxvAq25GSdu4Jtwh0uZIQ0I8awAegejTA',
    appId: '1:162614977353:web:536c44ebca0e6deb4e3098',
    messagingSenderId: '162614977353',
    projectId: 'basket-3ab3a',
    authDomain: 'basket-3ab3a.firebaseapp.com',
    storageBucket: 'basket-3ab3a.firebasestorage.app',
    measurementId: 'G-BTHR7ES08W',
  );

}